name: Test Suite

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test --parallel --coverage=.profile

      - name: Run test coverage reporter
        run: deno run --allow-all build/coverage.ts > build/coverage.json

      - name: Upload coverage as an asset
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: build/coverage.json
          compression-level: 0
